"""App-facing service layer for CLI and future desktop frontends."""

from .analysis import AnalysisResult, AnalysisService, GraphLoadSpec, ServiceWarning
from .compare import ArtifactDelta, compare_artifacts
from .findings import Finding, findings_for_analysis
from .queries import EdgeSummary, GraphQueries, NodeSummary
from .slices import GraphSlice, GraphSlices
from .workbench import (
    CoverageRow,
    BuildDiffRow,
    EvidenceMatrixRow,
    GraphLayer,
    InvestigationRecipe,
    TimelineGanttRow,
    TimelineRow,
    TimelineTreeItem,
    WorkbenchSession,
    compare_builds,
    coverage_rows,
    evidence_matrix_rows,
    evidence_report_html,
    evidence_bundle,
    filter_graph_layers,
    graph_layers,
    investigation_recipes,
    timeline_gantt_rows,
    timeline_rows,
    timeline_tree,
)

__all__ = [
    "AnalysisResult",
    "AnalysisService",
    "ArtifactDelta",
    "BuildDiffRow",
    "CoverageRow",
    "EdgeSummary",
    "EvidenceMatrixRow",
    "Finding",
    "GraphLayer",
    "GraphLoadSpec",
    "GraphQueries",
    "GraphSlice",
    "GraphSlices",
    "InvestigationRecipe",
    "NodeSummary",
    "ServiceWarning",
    "TimelineRow",
    "TimelineGanttRow",
    "TimelineTreeItem",
    "WorkbenchSession",
    "compare_artifacts",
    "compare_builds",
    "coverage_rows",
    "evidence_matrix_rows",
    "evidence_bundle",
    "evidence_report_html",
    "filter_graph_layers",
    "findings_for_analysis",
    "graph_layers",
    "investigation_recipes",
    "timeline_gantt_rows",
    "timeline_rows",
    "timeline_tree",
]
